### ISSUE TITLE
GPL code mixed in Tuple2f and SGImplify?

### ISSUE THREAD

**Issue by jboynes** [SignalK/signalk-core-java#3]
The [following comment](https://github.com/SignalK/signalk-core-java/blob/master/src/main/java/nz/co/fortytwo/signalk/util/Tuple2f.java#L15) implies there may be GPL code mixed in these files:

``` java
/*
 * ...
 * Copied from http://screamyguy.net/Tuple/, under GPL licence as stated on the site
 * Modified to handle GPX by R T Huitema 2013 for Freeboard
 */
```

If true this could cause GPL to apply to the whole distribution. The link is also now dead so its hard to verify the original license terms. To remove that ambiguity I propose to re-implement the decimation function from the original algorithm as I can't find an Apache licensed version out there.

**Comment by rob42** [comment]
Hmm..yes it looks like i overlooked this. much of the code came from my Freeboard project which is GPL, and when i created this one I tracked and replaced all the incompatible licences - but looks like I missed this one.
This routine is used to simplify the vessel track, so we dont store a zillion points on a almost straight line.
