### ISSUE TITLE
Set up distribution of core jar via a public Maven repository

### ISSUE THREAD

**Issue by jboynes** [SignalK/signalk-core-java#8]
The jar produced by this should be downloadable from a Maven repository so that is can be used by other SignalK/Java projects. Currently this project must be built locally before it can be used e.g. by signalk-server-java.

Suggested locations would be [jCenter](https://bintray.com/bintray/jcenter) or Sonatype's [OSS repo](http://central.sonatype.org/pages/ossrh-guide.html). Both need configuration by an authorized user, typically a collaborator on the project. Once write access to the repository is set up, deployment can happen automatically at the end of the Travis CI build.

**Comment by jboynes** [comment]
I set up a [temporary artifactory](http://ec2-52-91-140-52.compute-1.amazonaws.com/artifactory/libs-snapshot) and updated the build to use it. `mvn deploy` can now be used to make copies of this available for integration testing.

**Comment by rob42** [comment]
Closing as this is now possible through jitpack.io, and achieves the same. This can be revisited when we have more experience with the new build methods
